### ISSUE TITLE
RMS job exposing configurable default extensions to PATH and PYTHONPATH

### ISSUE THREAD

**Issue by markusdregi** [equinor/libres#1047]
**Introduction**
RMS is running in a separate environment with it's own Python interpreter. However, as RMS also serves the role of a workflow manager within our modeling pipeline, the users needs to be able to extend the RMS environment. In particular, we need to extend both `PATH` and `PYTHONPATH`. The need for passing a different `PATH` occurred quite recently due to RMS picking up an external Python interpreter if launched from within a virtual environment.

**Related work**
The recent work to facilitate `PATH` extensions can be found here. These are left here more as a reference, then necessarily recommended reading before the task is initiated.

- https://github.com/equinor/libres/pull/1046
- https://github.com/equinor/libres/pull/1041
- https://github.com/equinor/equilibrium/pull/42
- https://github.com/equinor/equilibrium/pull/39
- https://github.com/equinor/subscript/pull/217

**Task**
As of now the user will have to manually extend the RMS environment in their ERT configuration to be able to run RMS with what we in Equinor considers a default RMS environment. In particular, they will have to configure `RMS_PYTHONPATH` and `RMS_PATH_PREFIX` in their setup. The suggestion is that if a user only needs the "vanilla" environment, they will not have to do any configuration.

**Suggested approach**
I suggest that we extend the RMS job configuration file such that one for versions of RMS can specify a `RMS_PYTHONPATH` and `RMS_PATH_PREFIX` that is to be set as default. Something along the lines of:

```yaml
executable: /path/to/rms
threads: 1
env:
  10.0.0:
      RMS_PYTHONPATH: some/path
      RMS_PATH_PREFIX: some/other/path
   11.0.0:
      RMS_PYTHONPATH: some/path-11
      RMS_PATH_PREFIX: some/other/path-11
```

Then the RMS job bundles the potentially configuration from the user with the configuration and passes this on to the wrapper script. In particular, I would like to see for both `RMS_PYTHONPATH` and `RMS_PATH_PREFIX` the following priority: `paths/from/ERT-config:paths/from/configuration`.

When doing this it might be more sane to defer the transfer from `RMS_PYTHONPATH` to `PYTHONPATH` to the wrapper script and let it take responsibility of dealing with `RMS_PYTHONPATH` and `PREFIX_PATH`. Notice that this will also induce changes in the script in subscript, but I don't think it is very sane to let `RMS_PYTHONPATH` become `PYTHONPATH` before we actually are about to enter RMS.

**Notes**
- This also induces that the configuration of RMS in ert-configurations must be updated.
- The environment is deduced in the rms job in subscript, so we can at least use that as a reference for which paths needs to be included in equilibrium.

**Comment by berland** [comment]
Supported. 

Being able to delete RMS_PYTHONPATH from ERT configs is a considerable simplification.

**Comment by ManInFez** [comment]
> This also induces that the configuration of RMS in equilibrium must be updated.

Do you mean the configuration of RMS in ert-configurations?

**Comment by markusdregi** [comment]
Yes, my mistake @ManInFez. Corrected

**Comment by markusdregi** [comment]
Good @berland! Do you know if users are using this feature beyond retrieving the standard environment deployed?

Also, do you agree on the setup where potential configuration in ERT then takes precedence, but does not replace, what is in the default configuration?

**Comment by berland** [comment]
> Good @berland! Do you know if users are using this feature beyond retrieving the standard environment deployed?

I doubt they do anything else than experiment until it works..

> Also, do you agree on the setup where potential configuration in ERT then takes precedence, but does not replace, what is in the default configuration?

Yes, think so.
