### ISSUE TITLE
Shell scripts not properly installed as workflow jobs

### ISSUE THREAD

**Issue by berland** [equinor/libres#1064]
A workflow file with
```MAKE_DIRECTORY foo``` 

gives an error message:

`** Warning: The workflow file /tmp/pytest-of-berland/pytest-234/test_ert_integration0/wf_mkdir is not valid - make sure the workflow jobs are defined accordingly`

See https://github.com/equinor/semeio/pull/257 for an example that exposes bug.

This was supposedly solved in https://github.com/equinor/ert/pull/1029

**Comment by sondreso** [comment]
Fixed by https://github.com/equinor/libres/pull/1065
