### ISSUE TITLE
Problem getting the python test / development enviornment up and running

### ISSUE THREAD

**Issue by joakim-hove** [equinor/libres#1074]
I have problems getting the Python test & development up and running for libres. I execute the following small script:
```bash
#!/bin/bash

# Start with a clean Python environment
unset PYTHONPATH
unset LD_LIBRARY_PATH
python3 -m venv venv
source venv/bin/activate

git clone git@github.com:equinor/libres
pushd libres
pip install -r requirements.txt

python setup.py develop
```
The final `python setup.py develop` command fails with:
```
Traceback (most recent call last):
  File "setup.py", line 69, in <module>
    "-DECL_INCLUDE_DIRS=" + get_ecl_include(),
  File "setup.py", line 8, in get_ecl_include
    from ecl import get_include
ImportError: cannot import name 'get_include' from 'ecl' (/tmp/venv/lib/python3.7/site-packages/ecl/__init__.py)
```

The `ecl/__init__.py` file is entirely empty:
```bash
bash$ more /tmp/venv/lib/python3.7/site-packages/ecl/__init__.py
bash$
```

Any help appreciated.

**Comment by markusdregi** [comment]
Do you get the same error if you replace the last two commands with `pip install .`? That works locally on my machine at least, but is not the best for development.

I'm currently looking into trying to make running the tests a bit more streamlined...

**Comment by joakim-hove** [comment]
Not entirely sucessfull that either:  
```txt
  ....
  Collecting libecl
    Downloading https://files.pythonhosted.org/packages/a4/74/abceb7eabc0a87246eed3b0171824675f0c1466e2ead06b76856e240f74a/libecl-2.9.4-py3-none-any.whl
  Collecting distro (from scikit-build)
    Using cached https://files.pythonhosted.org/packages/25/b7/b3c4270a11414cb22c6352ebc7a83aaa3712043be29daa05018fd5a5c956/distro-1.5.0-py2.py3-none-any.whl
  Collecting packaging (from scikit-build)
    Downloading https://files.pythonhosted.org/packages/28/87/8edcf555adaf60d053ead881bc056079e29319b643ca710339ce84413136/packaging-20.7-py2.py3-none-any.whl
  Collecting ecl==2.9.4 (from libecl)
    Could not find a version that satisfies the requirement ecl==2.9.4 (from libecl) (from versions: 0.0.0)
  No matching distribution found for ecl==2.9.4 (from libecl)
  
  ----------------------------------------
Command "/tmp/venv/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-d9to0yox --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools setuptools_scm wheel scikit-build cmake ninja libecl" failed with error code 1 in None
```

**Comment by markusdregi** [comment]
Hmm, if you're not able to find a libecl version I'm thinking that is perhaps due to a incompatible environment with what we have currently built for. Assuming it is not a Windows machine, could it be due to an outdated `pip`-version? We do require a rather new `pip`...

**Comment by joakim-hove** [comment]
> [...] could it be due to an outdated pip-version? We do require a rather new pip...

OK - I added a `pip install --upgrade pip` to my install script and then the `pip install .` worked as it should

**Comment by markusdregi** [comment]
Neat! 👏

I've started on an attempt of a `src`-`tests` layout in #1075 as it seems to simplify using testing tooling a lot. I'll keep you posted.

**Comment by joakim-hove** [comment]
With the upgraded `pip` this also works:
```
pip install -r test_requirements.txt
python setup.py develop
python -m pytest python/tests
```
Although there many test failures and currently it seems to hang here:
```
python/tests/res/simulator/test_batch_sim.py FF.F.
```

**Comment by markusdregi** [comment]
Hmm, do you have a list of the failing tests or some stack trace to share? A typical reason why integration tests are failing is that people have a too low `ulimit` set. Could that be the issue?

**Comment by joakim-hove** [comment]
As mentioned it hangs on the `test_batch_sim.py` - but when I <kbd>Ctrl-c</kbd> I get a long traceback consisting of many occurences of:
```
Traceback (most recent call last):
  File "/tmp/venv/bin/job_dispatch.py", line 11, in <module>
    load_entry_point('equinor-libres', 'console_scripts', 'job_dispatch.py')()
  File "/tmp/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/tmp/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/tmp/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'job_runner'
```

**Comment by sondreso** [comment]
Try adding the python folder to `PYTHONPATH`, does that fix it?

**Comment by markusdregi** [comment]
Also, as seen in the CI you run the danger of picking up the `libres/python/job_runner` instead of the installed version (which includes the compiled libraries) and the former will definitively fail. I'm not sure how graceful the `cwrap` failure of not finding the libraries will be 🤷

**Comment by joakim-hove** [comment]
> Try adding the python folder to PYTHONPATH, does that fix it?

Yes - that fixed it!

**Comment by markusdregi** [comment]
Neat!

**Comment by markusdregi** [comment]
If you have time; could you check whether this branch also fixes your problem? The current recipe for running the tests are described in the PR description: https://github.com/equinor/libres/pull/1075

**Comment by joakim-hove** [comment]
OK - this script now works for me:
```bash
#!/bin/bash

rm -rf venv
rm -rf libres

unset PYTHONPATH
unset LD_LIBRARY_PATH
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip

git clone git@github.com:equinor/libres
pushd libres
pip install -r requirements.txt
pip install -r test_requirements.txt

python setup.py develop

export PYTHONPATH=$(pwd)/python
python -m pytest python/tests
popd
```

**Comment by joakim-hove** [comment]
> [...] could you check whether this branch also fixes your problem?

I will do that.

**Comment by markusdregi** [comment]
Thanks for the follow up @joakim-hove! The branch simplifying running the tests have now been merged with updated README. If new problems occur I sincerely hope you’ll open a new issue 👏
