### ISSUE TITLE
Possible to provide a pip package for python 3.9?

### ISSUE THREAD

**Issue by kjetil-lye** [equinor/libres#1093]
It seems the current version is not available for python-3.9 on pip. 

**Steps to reproduce**

1. Install python-3.9 together with pip and virtualenv.
2. Create a new virtualenv and activate

```bash
python3.9 -m venv .venv
source .venv/bin/activate
```
3. Install libres
```
pip install equinor-libres
```

Result:

```
ERROR: Could not find a version that satisfies the requirement equinor-libres (from versions: none)
ERROR: No matching distribution found for equinor-libre
```

Expected result: equinor-libres installs also for python3.9.

Note that following the same procedure for python3.8 works flawlessly.

[According to pypi](https://pypi.org/project/equinor-libres/), the pip package for libres only supports python versions up to python 3.8.

**Comment by markusdregi** [comment]
Hi @kjetil-lye and thanks for taking interest in this!

We would love to support 3.9, but as of now we have some dependencies that still do not support Python 3.9... We will add support whenever that becomes feasible, but until that time I hope you can live with a Python 3.8 installation ;)

Cheers,
Markus

**Comment by sondreso** [comment]
The latest beta release now has support for python 3.9 and will also be included in the final release: https://pypi.org/project/equinor-libres/10.1.0b2/
