### ISSUE TITLE
Leave message for user when MAX_RUNTIME kicks in

### ISSUE THREAD

**Issue by berland** [equinor/libres#1108]
When ERT kills realizations due  to MAX_RUNTIME, it is difficult for end-users to figure out that this is actually what happened.  A typical trace is f.ex:

```
ECLIPSE100                      : 11:39:32 .... 18:50:51   EXIT: 1/Process exited with status code 1
```

in `STATUS` and this looks identical to situations where Eclipse has crashed. In the ERT gui the realizations come up as "Failed" with no further explanation.

Since MAX_RUNTIME is in seconds, and timestamps in STATUS are as clock-times (with no dates), deducing that MAX_RUNTIME is the culprit is non-trivial. Also, the actual MAX_RUNTIME setting is hard to trace from the scratch disk without being informed about which ert config file has been used (this applies to those helping to debug).

Suggest to 

1:  Append a comment to the end of STATUS stating that a specific value of MAX_RUNTIME has been exceeded and therefore killed.

2: Give hints in the GUI for the same.

FYI: Current debugging procedure is at  https://wiki.equinor.com/wiki/index.php/FMU_debugging, section: Error: ERT realization runs fail with no clear message in the middle of a simulation

**Comment by markusdregi** [comment]
Thanks for the issue @berland. 1 can be solved, while 2 is wildly out of scope for ERT 2. For that one, stay tuned for ERT 3 and message passing...

If picked up I suggest we restrict the work entirely to 1.

**Comment by sondreso** [comment]
1 is not trivial either, as it means that the ERT client would need to modify the (potentially half written) status file after the job has been aborted 🙁

**Comment by berland** [comment]
3: Append a comment to any file in runpath with the message, so at least `ls -ltr` will uncover it.

**Comment by jondequinor** [comment]
Fixed in https://github.com/equinor/ert/pull/1636
