### ISSUE TITLE
New localisation functionality using row_scaling fails if grid size exceeds 62x62x62

### ISSUE THREAD

**Issue by oddvarlia** [equinor/libres#1131]
Preliminary testing of row_scaling functionality fails if grid size exceeds 62x62x62. The error message (if not segmentation fault appear) is Size mismatch between row_scaling and A matrix.
[Test localisation using new functionality.pptx](https://github.com/equinor/libres/files/6178615/Test.localisation.using.new.functionality.pptx)

**Comment by joakim-hove** [comment]
Fix here: https://github.com/equinor/libres/pull/1133
