### ISSUE TITLE
job_dispatch's event reporter should handle unresponsive EE

### ISSUE THREAD

**Issue by jondequinor** [equinor/libres#1153]
1. Make sure reporting does not halt on a slow EE (should be dealt with by the introduction of a queue https://github.com/equinor/libres/commit/63f65174c64955a8c2d673c5454b41d62a7c8901
1. If a `send()` fails, a strategy should be employed in order to ensure the message is eventually sent

**Comment by sondreso** [comment]
Do we agree that this is solved with the retry strategy in the client, or should we do something more? @jondequinor @mortalisk

**Comment by jondequinor** [comment]
Agreed👌🏻
