### ISSUE TITLE
Be able to get a list of nodes/nodenames from a modellparametergroup object

### ISSUE THREAD

**Issue by oddvarlia** [equinor/libres#1160]
A model parameter group   (created by local_config.createDataset(model_group_name)) can contain one or more model parameter nodes (which is specified in ERT config). There does not exist any python  method for this object to get the list of nodes (or nodenames). It will simplify the use of libres in some cases if it is possible to get the nodes within a group without having to store that information in additional data structure (e.g dict) in the application script and send it into all functions that need that information.

One example of a use case is to check which model parameters in nodes belonging to a model parameter group is active or not.
By retrieving the list of nodes from the group and the active list from the nodes this is possible, but  not yet without additional book-keeping in the application script.

**Comment by joakim-hove** [comment]
It is on my list to provide such a function; hopefully tomorrow.

**Comment by joakim-hove** [comment]
@oddvarlia : see https://github.com/equinor/libres/pull/1164
