### ISSUE TITLE
Editable install does not work as expected

### ISSUE THREAD

**Issue by sondreso** [equinor/libres#1162]
**Describe the bug**
Installing libres with `pip install -e` does not give the desired behaviour.

**To Reproduce**
1. `pip install -e .`
2. Edit some file
3. `ert gui my_config.ert`
4. Observe that the change you made is not included

**Expected behavior**
`pip install -e` works as it should and allows you to edit the installation.

**Enviromment**
 - OS: Mac and RHEL7
 - Python version: All

**Additional context**
This might be a bug in scikit-build, @dotfloat has the details on this.

**Comment by sondreso** [comment]
This is probably the reason: https://github.com/pypa/setuptools/issues/230

**Comment by sondreso** [comment]
Proposed solution: Remove `python` folder and move all modules up one level.

**Comment by jondequinor** [comment]
> This is probably the reason: https://github.com/pypa/setuptools/issues/230

We found that setuptools' setup function respected a root package_dir entry, whereas skbuild's setup function did not.

**Comment by sondreso** [comment]
Closed by https://github.com/equinor/ert/pull/1714
