### ISSUE TITLE
BatchSimulator should block on results()

### ISSUE THREAD

**Issue by agchitu** [equinor/libres#181]
The BatchSimulator.results() should block the calling context if there are still simulations that are running..

**Comment by markusdregi** [comment]
Why, you already have the functionality to `join` or to check if it is still `running`? I would say that it is unexpected for the `result` method to block, but that is just my opinion..

**Comment by agchitu** [comment]
The first reason, not the most important one is though is: the comment in the code says so:
```python
def results(self):
        """Will return the results of the simulations.
        This property will first block until all simulations have completed,
        and then it will return all the results which were configured with the
        @results when the simulator was created. .....
``` 

The second reason is that from the point of view of the user code, I would like no to be forced to manually have a waiting loop:
I want to say:
```python
sim_context = sim.start(....)
results = sim_context.results()
use(results)
```

I understand the utility of `if running()` but in the my context where I do not have to/care to monitor the simulation progress and I am interested in the results I like the shortcut.

**Comment by pgdr** [comment]
This was discussed in #168.  You are right that the docstring says it should block now, but that is an error.

The API is of course not set in stone, but I kind of like
```python
simulator.join()  # waiting ...
simulator.results()
```
better than
```python
simulator.results()  # ... what ?  why does this take time?
```

The change is done in [dc0e362](https://github.com/Statoil/libres/pull/168/commits/dc0e36200b7e345a63e61f95df41c4defbece2d8#diff-24858fbf8fd8cafcb4a455db89dd491bR43).

**Comment by agchitu** [comment]
@pgdr My impression is that this is a matter of personal preference. The wait()/join() is an extra, explicit step which I am forced to always use. For me it is natural to wait for results:
```python
sim.start()  # starting should be fast 
sim.results()  # evaluation if results should be slow
```
Anyway, it is not critical I have used the wait variant already.  However, it was enough to make it an issue.
I would make results blocking but implement the alternative as well for users that want more information while waiting for results.

**Comment by joakim-hove** [comment]
Through a more or less democratic process I will hereby close this with: https://github.com/Statoil/libres/pull/184
