### ISSUE TITLE
snake_oil fails to run

### ISSUE THREAD

**Issue by kjellkongsvik** [equinor/libres#191]
test-data/local/snake_oil/snake_oil.ert

Replacing JOBNAME with ECLBASE is a workaround

**Comment by markusdregi** [comment]
Thanks for reporting!

The bug can be reproduced by replacing `config_file = "${PROJECT_SOURCE_DIR}/test-data/local/snake_oil_no_data/snake_oil.ert"` with `config_file = "${PROJECT_SOURCE_DIR}/test-data/local/snake_oil/snake_oil.ert"`in _ERT_'s gui_test.
