### ISSUE TITLE
Consider adding a "stdout log level"

### ISSUE THREAD

**Issue by pgdr** [equinor/libres#214]
The current log level writes every message at that level or higher to file.

Should we have a different "stdout level" that makes every message over a given threshold written to stdout?

e.g.
```
LOG_LEVEL = INFO
LOG_STDOUT = ERROR
```
could write every message with `ERROR` or higher to terminal, whereas ever message with `INFO` or higher is written to the log file.

**Comment by joakim-hove** [comment]
Yes - maybe that is a good idea. The current functionality with optional `dup` to a stream is at least not very good.

Or we could have a system with log handlers? Let's discuss it.

**Comment by sondreso** [comment]
We are moving to python loggers
