### ISSUE TITLE
obs_vec activeStep does not raise error for more than one observation

### ISSUE THREAD

**Issue by eivindjahren** [equinor/libres#219]
In [obs_vector.py#L110](https://github.com/Statoil/libres/blob/f651c5d1b36fe2850a13dbf59adc8c07e42f5557/python/python/res/enkf/observations/obs_vector.py#L110) `if len(step_list):` should be `if len(step_list) == 1:` in order to conform to the specification of `activeStep()`.

**Comment by joakim-hove** [comment]
I agree - please make a PR

**Comment by pgdr** [comment]
Fixed in #220
