### ISSUE TITLE
Removing support for column major order

### ISSUE THREAD

**Issue by pgdr** [equinor/libres#258]
In the Matrix library, we support row and column major order.

If we don't use this feature, we should consider removing it and sticking to one specific order (the default).

If, however, we _do support and use this functionality_, I think this is a bug that should be fixed, or at the very least a function that could be improved.

```c
void matrix_fscanf_data( matrix_type * matrix , bool row_major_order , FILE * stream ) {
 int row,col;
 if (row_major_order) {
   for (row = 0; row < matrix->columns; row++) {
     for (col = 0; col < matrix->columns; col++) {
       __fscanf_and_set( matrix , row , col ,stream);
     }
   }
 } else {
   for (row = 0; row < matrix->columns; row++) {
     for (col = 0; col < matrix->columns; col++) {
       __fscanf_and_set( matrix , row , col , stream);
     }
   }
 }
}
```

**Comment by joakim-hove** [comment]
The memory stored matrix can only have one ordering, this function supports reordering when loading from disk - if we load data from disk at all I think we should support that switch. Might be improved though...

**Comment by pgdr** [comment]
But the two `if/else` sections are identical, and it only supports quadratic matrices?  That should at least be documented.

**Comment by joakim-hove** [comment]
Yes - it is probably a bug.
