### ISSUE TITLE
Possibility for user to add metadata to ERT observation file

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/libres#285]
**Feature request** _Possibility for user to add metadata to ERT observation file_

Elements of a typical observation file today:
```
SUMMARY_OBSERVATION THP_X-1H_2{ VALUE=407; ERROR=24; DATE=19/09/2003; KEY=WBP9:X-1H;};
GENERAL_OBSERVATION R_ABC-1AH{DATA=R_ABC-1AH_DATA; RESTART=1; OBS_FILE=../input/observations/rft/R_ABC-1AH_1986-09-10.obs;};
```
```
cat R_ABC-1AH_1986-09-10.obs

242.8  5
225.3  5
280.6  5
```
There is an internal workflow in Statoil which post-process RFT data (not developed by IT SI). It is somewhat cumbersome to use, when it comes to setting it up. E.g., the  `GENERAL_OBSERVATION R_ABC-1AH` in the example above needs a corresponding file called `R_ABC-1AH.txt` in the same folder, with content
```
cat R_ABC-1AH.txt

404131.72    7213542.64    4074.90    3014.26     G22
403577.27    7214600.92    5125.10    3049.13     G13
403893.25    7214280.17    5273.70    3424.03     G22
```
The script assumes this file exists. Columns are `x` coordinate, `y` coordinate, measured depth (MD), vertical depth (TVD) og zone name, for the different data points. The lines in these two files should correspond line by line. In addition, the date of the data points (even though there could easily be several days between when the data points were taken) is part of the `OBS_FILE` filename.

The reason this solution was chosen is probably that it is not possibly to add metadata (or comments to a `OBS_FILE`) in the ERT observation file. RFT was one example of `GENERAL_OBSERVATION` usage. Another common type of `GENERAL_OBSERVATION` is time-lapse gravity data, where metadata includes survey dates (base and repeat), and station names.

If metadata is possible to add, another common use case would be to add comments to some of the observations. The person setting up the observation file typically acquire knowledge about the quality of the data points. It would be nice if this knowledge could be stored in the setup as metadata (it could then also be visualized in other postprocessing tools like `webviz`). Today this knowledge is often lost (or hidden in some modelling pdf-report) if the person setting up the observation file leaves the modelling project.

A workaround for the end user could of course be to create another observation file (which supports metadata), and then have a script taking this as input and creating ERT-obs-file as output. However, that feels like a hack (and you will need to run this before ERT every time the observation file is changed, in order to be in sync). I.e. the best is probably to have the opportunity of adding generic metadata to the observation file format in ERT.

**Comment by anders-kiaer** [comment]
`yaml` could perhaps be better than `json` when/if changing to a new observation file format. The obs.file (at least part of it) is typically user generated, making `yaml` easier to work with. In addition, with `yaml` you can temporarily comment out blocks of the obs.file without actually removing data from the file (in case you want to include them again later).

**Comment by joakim-hove** [comment]
Yes - this is on the mental list.

**Comment by sondreso** [comment]
Will be resolved in a combination of new configuration and storage.
