### ISSUE TITLE
Error:rml_enkf.so: cannot open shared object file

### ISSUE THREAD

**Issue by pgdr** [equinor/libres#286]
Failed to load library:rml_enkf.so Error:rml_enkf.so: cannot open shared object file: No such file or directory 
** Warning: failed to load module from rml_enkf.so.

**Comment by joakim-hove** [comment]
OK - which environment is this?

**Comment by pgdr** [comment]
I've seen it several times, I think you get it if you just start everest on komodo (ert 2.3)

**Comment by joakim-hove** [comment]
OK
