### ISSUE TITLE
Ability to pass environment variables to forward model jobs.

### ISSUE THREAD

**Issue by joakim-hove** [equinor/libres#288]
This problem has come about due to RMS which has an embedded Python3 interpreter which can be used to write Python plugins, and the interaction with a Python2 environment. The situation is:

1. The user has created package with Python3 modules, located at `$USER_PYTHON3_PATH`
2. The script used by ERT to start up rms needs access to the normal ert Python2 environment during runtime.

The final step when the ert rms script starts the real rms is:
```python
os.execv( path_to_rms )
```
my suggestion is to allow a new keyword `EXEC_ENV` to be added to the job description files like:
```
EXEC_ENV  PYTHONPATH /some/python/path
```
then this env variable can be passed in the final `exec` call.

**Comment by markusdregi** [comment]
I believe this was resolved in #291. Please reopen if I'm wrong.
