### ISSUE TITLE
queue not open and not ready for use

### ISSUE THREAD

**Issue by pgdr** [equinor/libres#30]
Abort called from: `job_queue_check_open` (`$libres/libjob_queue/src/job_queue.c:820`)

Error message: `job_queue_check_open: queue not open and not ready for use; method job_queue_reset must be called before using the queue - aborting`

```
 #00 ???(..)                       in ~libecl/lib/util/util_abort_gnu.c:170
 #01 util_abort__(..)              in ~libecl/lib/util/util_abort_gnu.c:303
 #02 job_queue_check_open(..)      in ~libres/libjob_queue/src/job_queue.c:821
 #03 job_queue_run_jobs(..)        in ~libres/libjob_queue/src/job_queue.c:864
 #04 job_queue_run_jobs__(..)      in ~libres/libjob_queue/src/job_queue.c:1040
 #05 ????
 #06 clone(..)                     in ???
```

**Comment by pgdr** [comment]
This occurred while running IES on the `snake_oil` case.

**Comment by joakim-hove** [comment]
OK; my assumption here is that the IES run model holds on to *one* job_queue which is reused from one iteration to the next. Must make certain that each iteration gets a new fresh `job_queue`instance.

**Comment by pgdr** [comment]
outdated, wontfix
