### ISSUE TITLE
Should be libres instead of libecl?

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/libres#329]
Since `libecl` is currently mentioned so many places in https://github.com/Statoil/libres/blob/master/README.md#1-libecl, it could be that I’m misunderstanding the split between `libecl` and `libres`, but my current understanding is that at lot of the references to `libecl` should be to `libres` instead (even in the title of the section)?

**Comment by pgdr** [comment]
You are right that the README is outdated, but the very second line says
> You need libecl to build libres.

But the build instructions for `libecl` should admittedly be in the `libecl` repo.

Patches are most welcome!

**Comment by ManInFez** [comment]
Build instructions for libecl is now in the libecl repo
