### ISSUE TITLE
Request for workflow to run ES_MDA from existing prior

### ISSUE THREAD

**Issue by eivindsm** [equinor/libres#335]
I submit a request for a workflow/ job for running ES_MDA from an existing ensemble (prior). ERT version 2.2 had a job called MDA_ES, but this has been removed and did not allow for starting from existing prior.

**Comment by sondreso** [comment]
Was this solved by https://github.com/equinor/ert/pull/976?

**Comment by markusdregi** [comment]
Nope. However, if the goal is to "automise" the process of running ES-MDA I think the CLI is a better option (which now supports running ES-MDA)... What do you think @eivindsm ?

**Comment by markusdregi** [comment]
This is supported in CLI and hence I'm closing this issue.
