### ISSUE TITLE
Debug text from: enkf_obs_scale_correlated_std

### ISSUE THREAD

**Issue by joakim-hove** [equinor/libres#365]
The workflow function: enkf_main_std_scale_correlated_obs_JOB can be used to estimate correlations among observations and then subsequently inflate the observation std to take account of the correlations. 

The key function here is: enkf_obs_scale_correlated_std()

The task is to create some basic text output from this function which can be used to check the scaling factor calculated. This is interesting output, and in the future a "good" output module should probably be devised, for now we can go with printf. This should be included in 2.3 - and maybe even backported to stable.

**Comment by oyvindeide** [comment]
There is implemented some basic printing in #366, closing this.
