### ISSUE TITLE
Stuff from ert-statoil

### ISSUE THREAD

**Issue by joakim-hove** [equinor/libres#413]
**Forward models:**
1. Should use the rms functionality and remove it from ert-statoil.
2. Should use the shell utility stuff in libres and remove it from ert-statoil.

**site-config:**
Currently the site-config file is taken verbatim from ert-statoil and the file found in libres is completely ignored. We should start with the one in libres and then only append site-specific content from ert-statoil.

**Comment by jondequinor** [comment]
ert-statoil is effectively dead, so let's not do this.
