### ISSUE TITLE
Add forward model job: CAREFULL_COPY

### ISSUE THREAD

**Issue by joakim-hove** [equinor/libres#416]
This job already exists in ert-statoil. Should only copy if target does not already exist.

**Comment by markusdregi** [comment]
The job in _ert-statoil_ is located here: https://github.com/Statoil/ert-statoil/blob/master/etc/ERT/Scripts/carefull_copy.py

Should go here similarly to the other shell jobs. https://github.com/Statoil/libres/tree/master/share/ert/forward-models/shell
