### ISSUE TITLE
Local QUEUE; unable to stop/kill jobs 

### ISSUE THREAD

**Issue by eivindsm** [equinor/libres#417]
ERT seems to be unable to stop jobs submitted with 'Local QUEUE' . User reported this as a problem for the second time.  The problem is unrelated to the job and has been confirmed with rms and with flow.

To reproduce: submit job with local queuing system, kill the job from GERT and observe that thye process still runs on the machine.

**Comment by joakim-hove** [comment]
Is this in the current `stable` version or in the `testing` version? There have been significant changes to the `LOCAL` queue, so although this has not been consciously related problems have been solved and hopefully this has also been solved - by accident.

If you confirm that the problem persists also in the current `testing` it is obviously still a problem and we should solve it.

**Comment by eivindsm** [comment]
Issue exist in both versions. The kill button in gert kills job_dispatch.py but not sub processes. Tested with komodo 2018.03.03

**Comment by joakim-hove** [comment]
> Issue exist in both versions. The kill button in gert kills job_dispatch.py but not sub processes. Tested with komodo 2018.03.03

OK - good; then we have a bug.
