### ISSUE TITLE
Jinja2 templating in libres

### ISSUE THREAD

**Issue by markusdregi** [equinor/libres#426]
Today there is a job in _Everest_ making Jinja2 templating easily available to the users. Should we move this job to _libres_ to also allow _ERT_ users to utilise this?

A templating functionality of this kind was requested on yammer..

**Comment by joakim-hove** [comment]
The system with context variables and `<magic>` variables in ert is quite large and complex, it is very important and much used functionality. It works - to some extent - from a user perspective, but the implementation is complex and fragile.

So - I really support making a proper templating solution available in ERT, but we should be carefull to not just add yet-another-template-functionality to ERT without also cleaning up and removing much of what is there already. This is a quite significant task.

**Comment by markusdregi** [comment]
Needs #432

**Comment by markusdregi** [comment]
I completely agree @joakim-hove. As discussed (offline) I suggest that we first make a job for doing this templating for files in the forward model at the request of the user. This is already initiated by @DanSava and @ManInFez .

I then suggest to keep the current templating language alive in the `ERT`-configuration files until we have decided whether or not to push for `yaml`. If we do the later, then I guess we can decide whether we want to keep the `<magic>` variables alive in the old format, and move to `Jinja2` only for `yaml`, or if we should do a complete transistion..

**Comment by markusdregi** [comment]
Needs #437

**Comment by ManInFez** [comment]
This was solved https://github.com/equinor/libres/pull/443, right?

**Comment by ManInFez** [comment]
Closing as this was resolved!
