### ISSUE TITLE
Eclipse can fail without eclend

### ISSUE THREAD

**Issue by markusdregi** [equinor/libres#463]
Users have ECLIPSE 300 fail without it writing an ECLEND file as asserted here; https://github.com/Statoil/libres/blob/1e81773d5ad18f57bb9a90be2d31497b8667fcd7/python/res/fm/ecl/ecl_run.py#L284

The error message they get is then that the eclend file is missing, which is misleading, as the problem is with their eclipse setup..

**Comment by joakim-hove** [comment]
Is this a reported bug?

**Comment by markusdregi** [comment]
I experienced it together with a user while debugging an _Everest_ case of his. He was copying in the Eclipse files one by one, had forgotten to move the EGRID, which made Eclipse fail. But the error he got in the ERROR file from `eclipse300` was that the ECLEND was missing..

**Comment by joakim-hove** [comment]
> He was copying in the Eclipse files one by one, had forgotten to move the EGRID, which made Eclipse fail. But the error he got in the ERROR file from eclipse300 was that the ECLEND was missing..

Hmmm - I get a feeling there is some misunderstanding here ...

**Comment by sondreso** [comment]
Outdated, feel free to reopen if this is not correct
