### ISSUE TITLE
Analysis modules and settings

### ISSUE THREAD

**Issue by joakim-hove** [equinor/libres#483]
The analysis modules used for updates in ert have the ability to set variables by the user, this is not very much used, but is getting more relevant with the upcoming work here: #422. The current implementation and Python/C interface is complicated, messy and to a large extent hardcoded. 

My suggestion is that a proper `struct setting` - with Python wrapping and all - is created to faciltate proper introspection of the available settings between Python (GUI) and underlying C(++) implementation.

**Comment by joakim-hove** [comment]
@geirev : FYI

**Comment by markusdregi** [comment]
This sounds interesting! It is however a feature of _ERT_ that I'm not very familiar with. Could you elaborate on the intended usage of these variables, where they are currently stored, etc?

**Comment by joakim-hove** [comment]
The various analysis modules have internal settings which can be set by the user from the config file[1]. For instance to set the svd truncation for the module `STD_ENKF` you can add the following to the configuration file:
```
ANALYSIS_OPTION STD_ENKF TRUNCATION 0.95
```
The actual code path induced by this will be through [this](https://github.com/Statoil/libres/blob/master/lib/analysis/analysis_module.cpp#L351) and eventually the setting will be applied [here](https://github.com/Statoil/libres/blob/master/lib/analysis/std_enkf.cpp#L227). The intention is that this system should be used from the configuration file.

Then at some stage a system for setting these things run-time from the gui was devised, the system for runtime setting is very much bolted on, and only halfways well integrated with the underlying system which works through the config file. The gui system for configuration is invoked if you push the cogwheels besides the [STD ENKF] in the picture below

![settings](https://user-images.githubusercontent.com/1321665/51101083-69b01400-17d9-11e9-903d-49d38141c8c5.png)

For most modules the available settings is very few (only one ?!), but for the RML module there are suddenly 6-7 settings, and these settings are **hardcoded in the Python class** - extremely ugly. When the ies module from Geir comes this suddenly becomes more relevant, and the uglyness even more pervasive. As you can see from #422 there are some modifiications to these hardcoded settings [here](https://github.com/Statoil/libres/pull/422/files#diff-7499fdb0774e68c5622c767c9417ee74)

What I meant to raise with this issue was a discussion around these things.








[1]: The system available for the queue drivers is very similar.

**Comment by sondreso** [comment]
Discussion is stale, feel free to reopen if you want to continue the discussion.
