### ISSUE TITLE
Improve the STD_SCALE_CORRELATED_OBS workflow so that it can be combined with eg MDA

### ISSUE THREAD

**Issue by eivindsm** [equinor/libres#484]
The scaling applied to standard devs of observations by the workflow STD_SCALE_CORRELATED_OBS is currently overwritten by the inflation factors from ES MDA. This should be changed so that the two can be combined.

In general I propose better support for scaling factors, for instance by being able to define them in the observation file.

**Comment by markusdregi** [comment]
This has been resolved in the `misfit_preprocessor` in https://github.com/equinor/semeio
