### ISSUE TITLE
Arguments ignored in the ECLIPSE100 forward model?

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/libres#490]
It looks like the arguments for version and num-cpu in the [ECLIPSE100](https://github.com/equinor/libres/blob/master/share/ert/forward-models/res/ECLIPSE100) is ignored when the job is added.
`ARGLIST <ECLBASE> --version=<VERSION> --num-cpu=<NUM_CPU>`

**Comment by anders-kiaer** [comment]
This is a commonly encountered problem also in user provided forward models.
