### ISSUE TITLE
error: ‘buffer_fread_compressed’ was not declared in this scope

### ISSUE THREAD

**Issue by torch183** [equinor/libres#501]
Hi,

When building "lib/CMakeFiles/res.dir/enkf/field.cpp.o", I'm getting this error:

_[ 35%] Building CXX object lib/CMakeFiles/res.dir/enkf/field.cpp.o
/tmp/libres/lib/enkf/field.cpp: In function ‘void field_read_from_buffer(field_type*, buffer_type*, enkf_fs_type*, int)’:
/tmp/libres/lib/enkf/field.cpp:397:36: error: ‘buffer_fread_compressed’ was not declared in this scope
                           byte_size);
                                    ^
/tmp/libres/lib/enkf/field.cpp: In function ‘bool field_write_to_buffer(const field_type*, buffer_type*, int)’:
/tmp/libres/lib/enkf/field.cpp:540:62: error: ‘buffer_fwrite_compressed’ was not declared in this scope
   buffer_fwrite_compressed( buffer , field->data , byte_size );
                                                              ^
make[2]: *** [lib/CMakeFiles/res.dir/enkf/field.cpp.o] Error 1
make[1]: *** [lib/CMakeFiles/res.dir/all] Error 2
make: *** [all] Error 2_

Am I missing some prerequisites? 
I've successfully built libecl prior to this.
cmake arguments are:
-DENABLE_PYTHON=ON -DCMAKE_INSTALL_PREFIX=~/bin/ert -DCMAKE_PREFIX_PATH=~/bin/ert

I've run this on both Ubuntu 18.04 and CentOS 7.6
Any tips would be appreciated

**Comment by joakim-hove** [comment]
> Am I missing some prerequisites?

Yes you are missing the `zlib-devel` package; but that is quite opaque and it is really bug in the build system that you get the message in this way. To solve this you should install the `zlib-devel` package and then rebuild & reinstall libecl

**Comment by torch183** [comment]
Ah, thanks. I was actually sort of on the right track then. I already installed zlib-devel, but I didn't think to try rebuilding libecl. Libres completed the build process now. Thanks for a super quick response!

**Comment by joakim-hove** [comment]
> Libres completed the build process now.

:+1:
