### ISSUE TITLE
Improve `zlib-devel` dependency detection

### ISSUE THREAD

**Issue by markusdregi** [equinor/libres#502]
See among other #501 for the effect of this problem.

The short story is that _libecl_ only requires `zlib` to compile, however _libres_  requires _libecl_ to be compiled with _zlib-devel_. Hence, _libecl_ never complains and _libres_ never detects this; yielding odd error messages. This should be improved.

**Comment by jondequinor** [comment]
This is a transitive dependency we currently leave as an exercise for the user to solve. Even with detection, it will be extremely irritating having to re-compile `libecl` with `zlib-devel` after `libres` complains.

`libecl` should fail if not compiled with `zlib-devel`.
The only other alternative _I_ see is that `libres` does not require `libres` to be compiled with `zlib-devel`.

**Comment by markusdregi** [comment]
Yes, only argument to keep this in `libres` is that `libecl` alone will indeed function without `zlib-devel`. But perhaps it is not worth the cost of potentially detecting the problem?

**Comment by markusdregi** [comment]
This hits very few people these days as most use the packages distributed via PyPI. Closing this as a won't fix.
