### ISSUE TITLE
Parallel initialization of ensemble

### ISSUE THREAD

**Issue by markusdregi** [equinor/libres#504]
Previously the initialization of the ensemble was done in parallel, but this had to be removed due to an unresolved bug that appeared.

The performance impact of this serialization should be evaluated at some point.

The changes can be found here: https://github.com/equinor/libres/pull/364

**Comment by jondequinor** [comment]
Parallelization isn't just having code bathe in a thread pool, it needs to be catered for at the architectural level.

I suggest this issue could rather become a discussion around the venues for parallelization in the architecture of the new storage solution.

**Comment by markusdregi** [comment]
I agree
