### ISSUE TITLE
Revise the structure of parameters.json

### ISSUE THREAD

**Issue by markusdregi** [equinor/libres#516]
**Background:**
The parameters to a forward model is now dumped to the runpath in a file called `parameters.json`, enabling the forward model to tool on top of this. The syntax of this file is based on the key-syntax used earlier in ERT (`key1:key2` etc).

As we are moving in the direction of `json` and `yaml` anyway, I would argue that we should take this with us into this process and dump the keys as full blown `json` instead.

**Example:**
Say that you have a `GEN_KW` named `X` with variables `A`, `B` and `C` (taking the values 1, 2 and 3 respectively). Today the content of `parameters.json` would be:
```json
{
"X:A": 1,
"X:B": 2,
"X:C": 3
}
```

I think it should be like this instead:
```json
{
  "X": {
    "A": 1,
    "B": 2,
    "C": 3
  }
}
```

**Relevant code:**
https://github.com/equinor/libres/blob/8205271b080b787046b3814e9a64a4cc2e230313/lib/enkf/value_export.cpp#L157

**Comment by ManInFez** [comment]
The parameter.json holds both types, to preserve backwards compatibility

```void value_export_json(const value_export_type * value) {
  std::string filename = value->directory +"/" + value->base_name + ".json";
  backup_if_existing(filename.c_str());

  if (!value->values.empty()) {
    FILE * stream = util_fopen( filename.c_str() , "w");
    fprintf(stream, "{\n");
    generate_hirarchical_keys(value, stream);
    generate_comosite_keys(value, stream);
    fprintf(stream, "}\n");
    fclose( stream );
  }

}
```
generate both hirarchical and composite keys. (I see now that there is a typo in the code...)

**Comment by ManInFez** [comment]
Closing issue, composite keys should disappear in V3.0
