### ISSUE TITLE
Revise workflows included in the repo

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/libres#521]
It appears that the workflows deep down in the `share` sub-folder are not used anywhere and there is no way to know whether they work or not.
In particular, we have found out that `share/ert/workflows/jobs/internal/config/RUN_SMOOTHER` crashes (in a pretty obvious way, the code sets `run_context=NULL` and then tries to access it).

It is not healthy to have undocumented untested unused code in the repo. We should evaluate which ones of those workflows are used by anyone (shall we ask on the ERT channel on yammer/slack) kick out the unused ones and write tests & documentation for the ones that are used

**Comment by jondequinor** [comment]
Since we now have `semeio` we could migrate these jobs and at the same time document and test them.

**Comment by jondequinor** [comment]
@sondreso what would you say the state of this issue is?

**Comment by sondreso** [comment]
We want to move all job and workflow jobs to semeio, but the current blocker is Everest not having a plugin system. This is being worked on, so after that we can proceed with this issue!

**Comment by markusdregi** [comment]
Created a new issue in ERT here: https://github.com/equinor/ert/issues/1880
