### ISSUE TITLE
Implement python comparison for each of the child configurations

### ISSUE THREAD

**Issue by markusdregi** [equinor/libres#532]
To enable logging if new and old construction differ. Create issues for each of the child configs and do one at the time!

Finished:

- rng config - depends on: https://github.com/equinor/libres/issues/533
- log config - depends on:  https://github.com/equinor/libres/issues/550
- queue config - depends on: #565 
- plot config - depends on #560
- site config - depends on: #555
- subst config - depends on: #563
- workflow_list - depends on: #580 
- hook_manager - depends on: #583
- analysis config - depends on: #576
- ecl_config - depends on #587
- model_config - depends on: #593 
- ensemble_config - depends on: #601
- templates - depends on: #595

In progress:
res config - depends on: #659

Still to go:

**Comment by ManInFez** [comment]
site config - depends on: #555 
subst config - depends on: #563

**Comment by markusdregi** [comment]
Resolved for all child configs
