### ISSUE TITLE
Make constructors that takes all necessary data

### ISSUE THREAD

**Issue by markusdregi** [equinor/libres#534]
Make new constructors for all of the child configs that gets all relevant data already processed as arguments to the constructor.

Finished
- rng config - depends on: https://github.com/equinor/libres/issues/535
- log config - depends on: https://github.com/equinor/libres/issues/549
- plot config - depends on: https://github.com/equinor/libres/issues/553
- site config -  depends on: #556
- queue config - depends on: #575 
- subst config - depends on #562
- analysis iter config - depnds on: #585 
- workflow_list - depends on: #580 
- hook_manager - depends on: #583
- analysis config - depends on: #576 and #585 
- ecl_config - depends on: #587 
- model_config - depends on: #593  
- ensemble_config - depends on: #601 
- templates - depends on: #595

Still to go:

**Comment by ManInFez** [comment]
site-config - depends on: #556

**Comment by ManInFez** [comment]
subst_config - depends on #562

**Comment by markusdregi** [comment]
Resolved for all child configs
