### ISSUE TITLE
Config translater

### ISSUE THREAD

**Issue by markusdregi** [equinor/libres#536]
Implement functionality to translate either `ResConfig` or `ConfigContent` to a dict and list bundle that can be passed in as a config to `ResConfig` init.

Probably a static method in `ResConfig`.

**Comment by xjules** [comment]
@markusdregi Can you elaborate a bit on this: `... can be passed in as a config to ResConfig init.`?
After discussion with @oyvindeide this is to list all config parameters as loaded from ert file.

**Comment by xjules** [comment]
I think that having ResConfig `to_dict` method would make sense, but naturally to have it clean and nice it would be great that each subconfigs has it's own export to dict function.

**Comment by sondreso** [comment]
Not aligned with current development
