### ISSUE TITLE
Remove duplicate files existing in ert

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/libres#541]
The shared gui folder exists in both `libres` and `ert`, and is also installed from both repositories. Whatever is in `ert` will overwrite `libres`

https://github.com/equinor/libres/tree/master/share/ert/gui

Remove the `share/ert/gui` in `libres

Similar issue in ert: https://github.com/equinor/ert/issues/319

**Comment by ManInFez** [comment]
share folder does not exist in ert anymore :)
