### ISSUE TITLE
Compiling of ensemble_config.cpp fails

### ISSUE THREAD

**Issue by geirev** [equinor/libres#543]
[ 20%] Building CXX object lib/CMakeFiles/res.dir/enkf/ensemble_config.cpp.o
/private/geve/ERT/libres/lib/enkf/ensemble_config.cpp: In function ‘bool ensemble_config_GEN_DATA_require_summary(const ensemble_config_type*)’:

/private/geve/ERT/libres/lib/enkf/ensemble_config.cpp:818:63: error: cannot convert ‘const std::map<std::basic_string<char>, enkf_config_node_struct*>’ to ‘const hash_type* {aka const hash_struct*}’ for argument ‘1’ to ‘hash_iter_type* hash_iter_alloc(const hash_type*)’
   hash_iter_type * iter = hash_iter_alloc(config->config_nodes);
                                                               ^
/private/geve/ERT/libres/lib/enkf/ensemble_config.cpp:821:115: error: cannot convert ‘const std::map<std::basic_string<char>, enkf_config_node_struct*>’ to ‘const hash_type* {aka const hash_struct*}’ for argument ‘1’ to ‘void* hash_get(const hash_type*, const char*)’
     const enkf_config_node_type * config_node = (const enkf_config_node_type *)hash_get(config->config_nodes , key);
                                                                                                                   ^
make[2]: *** [lib/CMakeFiles/res.dir/build.make:3138: lib/CMakeFiles/res.dir/enkf/ensemble_config.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:4801: lib/CMakeFiles/res.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
[  0%] Building CXX object lib/CMakeFiles/res.dir/enkf/ensemble_config.cpp.o
/private/geve/ERT/libres/lib/enkf/ensemble_config.cpp: In function ‘bool ensemble_config_GEN_DATA_require_summary(const ensemble_config_type*)’:
/private/geve/ERT/libres/lib/enkf/ensemble_config.cpp:818:63: error: cannot convert ‘const std::map<std::basic_string<char>, enkf_config_node_struct*>’ to ‘const hash_type* {aka const hash_struct*}’ for argument ‘1’ to ‘hash_iter_type* hash_iter_alloc(const hash_type*)’
   hash_iter_type * iter = hash_iter_alloc(config->config_nodes);
                                                               ^
/private/geve/ERT/libres/lib/enkf/ensemble_config.cpp:821:115: error: cannot convert ‘const std::map<std::basic_string<char>, enkf_config_node_struct*>’ to ‘const hash_type* {aka const hash_struct*}’ for argument ‘1’ to ‘void* hash_get(const hash_type*, const char*)’
     const enkf_config_node_type * config_node = (const enkf_config_node_type *)hash_get(config->config_nodes , key);
                                                                                                                   ^
make[2]: *** [lib/CMakeFiles/res.dir/build.make:3138: lib/CMakeFiles/res.dir/enkf/ensemble_config.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:4801: lib/CMakeFiles/res.dir/all] Error 2
make: *** [Makefile:128: all] Error 2

**Comment by joakim-hove** [comment]
Hmmm - is this a reasonably clean state - git wise?

**Comment by geirev** [comment]
Should be, fetched, merged and rebased IES2, and then it did not compile. I can try again tomorrow.

**Comment by joakim-hove** [comment]
OK - I have now checked out your version of the IES2 branch as it is here: https://github.com/equinor/libres/pull/422 - that *Works on my machine*&trade;

**Comment by geirev** [comment]
It is the changes in lib/enkf/ensemble_config.cpp below that does not compile on my system.
https://github.com/equinor/libres/pull/422/files#diff-59efb47611a9a5c85f10e756b085bce9R817

I don't know this code but assume is something that was added for IES2 or can we revert to master for this routine?

**Comment by geirev** [comment]
Probably something is garbled. I pushed my current version to IES2X 
https://github.com/geirev/libres/tree/IES2X

**Comment by joakim-hove** [comment]
OK - I have made this PR: https://github.com/geirev/libres/pull/16 into your IES2X branch - that should fix it.

**Comment by geirev** [comment]
Done. Thanks!
