### ISSUE TITLE
Installation overrides ecl config

### ISSUE THREAD

**Issue by markusdregi** [equinor/libres#547]
When installing ecl and rms forward models, the rms config is left as is if it exists, while the ecl config is overwritten every time...

**Comment by ManInFez** [comment]
rms_config.yml is installed using install_example()
eclXXX_config.yml is installed using configure_file(..., COPYONLY)

**Comment by ManInFez** [comment]
We should pick one behavior, but which one is up for debate.

**Comment by markusdregi** [comment]
I agree. I would assume the `rms` behaviour is the easiest to work with?

**Comment by ManInFez** [comment]
Although, increases the risk of being stuck on a "problem" if you have a broken config? @andreabrambilla argued that when  you install libres you would expect a clean install?

**Comment by andreabrambilla** [comment]
Probably the right thing to do would be to ask the user, but I am not sure how easily that can be done. 
Alternatively we could backup the existing config files and show a warning to the user about what happened

**Comment by sondreso** [comment]
While this specific issue still exists, you can now override the ecl/rms config using the plugin system
