### ISSUE TITLE
run example.ert using ert_tui

### ISSUE THREAD

**Issue by xclmj** [equinor/libres#574]
Hi, all,

  I have successfully install the OPM and ERT in my computer.  When I use the ert_tui  to test  example.ert  by the command line  ert_tui example.ert .  I encounter the following problem as follows:

Abort called from: util_abort_signal (.../libecl/lib/util/util.c:4410) 

Error message: Program received signal:11

--------------------------------------------------------------------------------
 #00 util_abort__(..)                                                              in .../libecl/lib/util/util_abort_gnu.c:173
 #01 ???? 
 #02 ert_run_context_get_mode(..)                                                  in .../libres/lib/enkf/ert_run_context.cpp:336
 #03 enkf_main_init_run(..)                                                        in .../libres/lib/enkf/enkf_main.cpp:1606
 #04 enkf_main_run_simple_step(..)                                                 in .../libres/lib/enkf/enkf_main.cpp:1654
 #05 enkf_main_run_smoother(..)                                                    in .../libres/lib/enkf/enkf_main.cpp:1664
 #06 _Z21enkf_tui_run_smootherPv(..)                                               in ???
 #07 menu_run(..)                                                                  in ???
 #08 _Z17enkf_tui_run_menuPv(..)                                                   in ???
 #09 menu_run(..)                                                                  in ???
 #10 _Z18enkf_tui_main_menuPv(..)                                                  in ???
 #11 main(..)                                                                      in ???
 #12 __libc_start_main(..)                                                         in /build/glibc-77giwP/glibc-2.24/csu/../csu/libc-start.c:325
 #13 _start(..)                                                                    in ???
--------------------------------------------------------------------------------

Do you know how to solve this problem?

best regard

**Comment by markusdregi** [comment]
Closed due to duplicate issue: https://github.com/equinor/ert/issues/372
