### ISSUE TITLE
util_abort deadlocks if too many files open

### ISSUE THREAD

**Issue by mortalisk** [equinor/libres#605]
util_abort has a mutext which it locks before logging to a file. If the opening of the file fails (in this case because of too many open files), then it calls util_abort again, trying to lock the same mutex, annd it deadlocks

the mutex lock is here: https://github.com/equinor/libecl/blob/7abee4f1a19dbba0c845e3dc23f7950021e12059/lib/util/util_abort_gnu.c#L251

the offending call that calls util_abort again is here: https://github.com/equinor/libecl/blob/7abee4f1a19dbba0c845e3dc23f7950021e12059/lib/util/util_abort_gnu.c#L300

which ends up here: https://github.com/equinor/libecl/blob/7abee4f1a19dbba0c845e3dc23f7950021e12059/lib/util/util.c#L4156

**Comment by sondreso** [comment]
This problem has not appeared in a long time, feel free to reopen if it happens again
