### ISSUE TITLE
file handles are not closed

### ISSUE THREAD

**Issue by mortalisk** [equinor/libres#606]
some code opens many files, and they are not closed. This is probably because of some circular references in python opbjects preventing them from being collected properly. This makes tests fail, specifically when including the equinor tests, as they open many files.

This was encountered when the test_ert_context.py test stopped. It was waiting for jobs to finish, but the jobs had deadlocked because they were trying to open files, failed, and were trying to log this with util_abort, which deadlocked because of a bug in util_abort (see other issue #605)

The tests then stops on this line: https://github.com/equinor/libres/blob/df0f6c44d8341b281898912a1635fa9860a7b284/lib/enkf/block_fs_driver.cpp#L447

Which is just incidentally because the jobs are trying to write to files, fail, and then deadlocks in util_abort.

**Comment by oyvindeide** [comment]
Not an ideal solution, but have increased the max number of files open on Jenkins to make the tests run.

**Comment by sondreso** [comment]
We are moving away from the libres fs
