### ISSUE TITLE
Forward model COPY_DIRECTORY - confusing beahviour

### ISSUE THREAD

**Issue by eivindsm** [equinor/libres#608]
Strange behavior for forward model COPY_DIRECTORY: When destination folder exist it creates a new directory within the existing. Eg COPY_DIRECTORY (<FROM>=foo, <TO>=bar) crates bar/bar/foo when bar already exists. If bar does not exist it becomes a copy of foo, as expected.

**Comment by ManInFez** [comment]
This is the same behavior as cp -r "src" "dst" in unix.

**Comment by markusdregi** [comment]
This will cause the forward model to behave differently if resubmitted. The better solution is probably to deviate from the standard shell commands and copy as Eivind suggests.
