### ISSUE TITLE
MIN_REALIZATIONS does not work as expected for small ensemble sizes

### ISSUE THREAD

**Issue by eivindsm** [equinor/libres#609]
Kw MIN_REALIZATIONS does not work as expected if a percentage is set and the ensemble size is small. Eg MIN_REALIZATIONS 2%, will halt if 4 out of 5 realizations are successful. Clearly not as advocated. It does however work as expected when ensemble size is big.

Running small ensemble sizes makes sense during testing.

**Comment by eivindsm** [comment]
Reading the docs and testing leads me to the following hypothesis: 2% of 5 is interpreted / rounded to 0 which is short hand notation for all realizations. I suggest that we issue a warning if user input is rounded to zero and that the popup error message is improved to include information on the limits to make it explicit for the user.

**Comment by markusdregi** [comment]
Sounds like a good patch for now.

In the future I would advocate that we use `None` (`~` in yaml-lingo) to denote none, an unbounded value or similar. The usage of `0` is a bit cumbersome at times.
