### ISSUE TITLE
Smoother update executed even though no valid observations are loaded

### ISSUE THREAD

**Issue by eivindsm** [equinor/libres#610]
User reports situation in which refcase was not successfully loaded and ERT did not have and valid observations, and still continue from iter-0 to iter-1 performing a meaningless smoother update. A warning is issues when refcase is not loaded, but ERT continues. Update log confirms that there are no observations.

**Comment by andreabrambilla** [comment]
I guess the correct behavior would be terminating with an error, but what is the exact error situations that we need to intercept? The refcase not being loaded correctly, or not having observations?
Is there a case we can use to reproduce the issue?

**Comment by eivindsm** [comment]
Yes, I'm thinking termination with an error. The refcase not being able to load might not necessarily be critical. Performing an update without any observations makes no sense, and is a very strong indication that  something is not according to the users intention. Test case confirming the issue created at: eism@st-linrgs096:/project/fmu/tutorial_ert/users/eism/r003/r003_20190416/ert/model/debug_27_6_2019.ert 

The following warnings are issued to the terminal: 
** Warning: loading refcase:/project/fmu/tutorial_ert/users/eism/r003/r003_20190416/ert/input/refcase/model/REEK_REF_BLABLA failed 
** Warning: failed to load observation data from: /project/fmu/tutorial_ert/users/eism/r003/r003_20190416/ert/input/observations/observations_historyobs.txt
At this point the the users should have been prevented from running anything but ensemble experiment.

**Comment by andreabrambilla** [comment]
It seems to behave correctly
```
(bleeding) [abramb@st-linrgs204 tmp]$ ert cli --mode ensemble_smoother --target-case mytestcase ert_tut_20190416/ert/model/debug_27_6_2019.ert 
** Warning: 'PLOT_SETTINGS' is ignored- use the general dialog windows instead. 
** Warning: loading refcase:/private/abramb/tmp/ert_tut_20190416/ert/input/refcase/model/REEK_REF_BLABLA failed 
** Warning: failed to load observation data from: /private/abramb/tmp/ert_tut_20190416/ert/input/observations/observations_historyobs.txt 
ERROR:root:No observations loaded. Unable to perform model update.
(bleeding) [abramb@st-linrgs204 tmp]$ 
```
