### ISSUE TITLE
Treatment of paths when using dict

### ISSUE THREAD

**Issue by xjules** [equinor/libres#621]
There is an ambiguity of what is the current working dir (`CWD`) used for obtaining the absolute path for files in the config file. Since there is none, I reckon there should be a `CWD` config key potentially, which sort of could replace the location of config file?

**Comment by andreabrambilla** [comment]
I would argue that the `CWD` is actually irrelevant. When we are writing a config file, the only interesting path is the the `CONFIG_DIR` (and the RUNPATH, but that's a different story).
When initializing objects from a dictionary, either the dictionary should contain the path to some sort of "project directory", or there should be a function that gives us that path

**Comment by markusdregi** [comment]
There is already a concept of `CWD` in _libres_ (see https://github.com/equinor/libres/blob/0fb768d834b77de0fa343269d46285e2ec560e5c/python/res/enkf/subst_config.py#L43). In particular, it is equivalent to `CONFIG_PATH`.

**Comment by markusdregi** [comment]
I agree that it is not always immediately clear what a path is relative to, but that can be fixed in the future by requiring more paths to be absolute. We can evaluate this while creating the new configuration file layout 👍 

Or did you have something else in mind @xjules ?

**Comment by xjules** [comment]
@markusdregi Basically that was the point - the paths (at least those that point towards inputs) should be absolute. 
@andreabrambilla Yes, I found `CONFIG_DIR` value, which servers the purpose sufficiently.

**Comment by xjules** [comment]
@markusdregi Basically solved by #562
