### ISSUE TITLE
RMS_BATCH failing shows as success in status.json

### ISSUE THREAD

**Issue by ManInFez** [equinor/libres#629]
Running reek without sourcing SDP_baschrc will cause RMS_BATCH to fail. However it is still shown as success in the status.json file

EXIT file:
``` <error>
  <time>13:16:41</time>
  <job>RMS_BATCH</job>
  <reason>Could not find target_file:RMS_TARGET.INC</reason>
  <stderr>
sh: make_3dgrid_regions: command not found
</stderr>
  <stderr_file>/scratch/ert_fmu/musiv/1_r001_reek/realization-0/iter-0/rms.stderr.36</stderr_file>
</error>```

status.json
```
        {
            "status": "Success",
            "name": "RMS_BATCH",
            "stdout": "",
            "start_time": 1564398912.0,
            "end_time": 1564398941.0,
            "stderr": "",
            "error": null
        },
```

**Comment by andreabrambilla** [comment]
possibly related to #616

**Comment by markusdregi** [comment]
Considering this a won't fix.
