### ISSUE TITLE
Res config - constructor and test 

### ISSUE THREAD

**Issue by xjules** [equinor/libres#659]
- Update res config with dictionary
- test function that compares all the subconfigs initiated via dictionary

**Comment by xjules** [comment]
@ManInFez We should look at `__repr__` functions of configs, since it crashes when initializing configs from dict.

**Comment by markusdregi** [comment]
Although being a first iteration (this will definitively have to be iterated a couple of times), we should still have an upfront discussion about the layout and initial keywords to include.
