### ISSUE TITLE
job max_running likely broken due to TOC/TOU-like issues

### ISSUE THREAD

**Issue by jondequinor** [equinor/libres#661]
There is a Time-Of-Check Time-Of-Use bug in the `check_license` function for a job.

An `os.stat` is performed where the number of hard links are counted. Based on this count, a hard link is created or not. If not, the check sleeps.

Given that multiple processes run multiple jobs thus multiple concurrent `check_licenses`, this could lead to more licensed jobs running than `max_running` allows.

A non-portable solution could require minimal additional work using [fcntl](https://docs.python.org/3/library/fcntl.html).

A portable solution could be solved by implementing a local licensing server.

**Comment by joakim-hove** [comment]
None of my business - but if you were to ask me I would say rip it out and forget it. The "license" feature was implemented and used briefly at a time when the availability of some third party  software was very restricted.

**Comment by markusdregi** [comment]
Thanks for the input @joakim-hove :+1: I agree that we should resolve this by removing the functionality then...
