### ISSUE TITLE
Make validation of independent childs

### ISSUE THREAD

**Issue by markusdregi** [equinor/libres#664]
For each of the independent child configurations we should make functionality for validating the input. Each subconfig should implement the following two functions in Python:

```python
# Indicate whether the subconfig is valid or not
@ property
def is_valid():

# Give a non-empty list of descriptive errors if not valid,
# if not an empty list should be returned
@ property
def errors():
```

Using schemas are encouraged.

Depends on:
- subst_config (https://github.com/equinor/libres/issues/713)
- site_config (https://github.com/equinor/libres/issues/717)
- rng_config (https://github.com/equinor/libres/issues/718)
- analysis_config (https://github.com/equinor/libres/issues/719)
- ecl_config (https://github.com/equinor/libres/issues/720)
- log_config (https://github.com/equinor/libres/issues/721)
- queue_config (https://github.com/equinor/libres/issues/722)

**Comment by sondreso** [comment]
Not aligned with current development
