### ISSUE TITLE
KEEP_QSUB_OUTPUT can make jobs crash silently

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/libres#672]
The line `QUEUE_OPTION TORQUE KEEP_QSUB_OUTPUT 1` should `libres` to tell `qsub` to keep the error and output streams. In practice libres adds the command line option `-k oe` to the `qsub` invocation. (see https://www.pbsworks.com/pdfs/PBSRefGuide18.2.3.pdf page RG-207).
This caused a curious problem on a cluster running PBS. A job would start, and seemingly complete correctly (the `OK` file is created`), but the job immediately disappears from the report produced by `qstat`, and this makes `libres` hang (cause it cannot detect that the job has completed).
We guessed that "keeping the streams" means dumping them to disk somewhere, and we may not have write access to that somewhere (or somewhere is deleted before the files are dumped).

Overall, that feature in libres is very little used, so we could consider just remove it from the libres configuration. Better solutions might involve digging into the the PBS documentation

**Comment by sondreso** [comment]
We are moving away from the old queue drivers, and the torque driver is not used much as of today either
