### ISSUE TITLE
First iteration of libres data api

### ISSUE THREAD

**Issue by markusdregi** [equinor/libres#675]
We want to design a data api for libres storage. The first iteration should contain an api 
specification together with a mocked implementation of data.

What we want to enable the consumer to do is:
- Plot time series data from the individual ensemble members, together with the corresponding observations.
- Plot statistics (mean, 10 and 90 percentiles) time series of time series, together with the corresponding observations.
- Scatter plot of parameters
- Possibility of comparing two cases
- Activate and deactivate observations in the visualisations (changes are propagated back into ERT)
- Linking and brushing (selecting a subset of the points in the parameter scatter plot and have only the corresponding ensemble members  visualised in the time series plots).

The necessary capabilities are:
- cases,
- the realisations in each case,
- the time series labels in each case,
- the parameter labels in each case,
- the time series data for a specific label, case and realisation,
- the parameter values for a specific label, case and realisation,
- the observation labels,
- the observation values for a specific label,
- possibility for submitting an active vector for the observations

**Comment by mortalisk** [comment]
Reviewer should not look at code. Only the API is interesting at this point. This is still a work in progress, but needs more input before we continue working.

The swagger.yml file is not really telling the truth, it is an implementation detail at this point, so don't look at that either.

New repository here: https://github.com/equinor/ert-mock-api

Is still lacking observations activation/deactivation.

**Comment by oysteoh** [comment]
trying to navigating the api fail hard on selecting project
```
glob_pattern = folder + project_name + "/" + config["runpath"].replace("%d", "0", ).replace("%d", "*") 
UnboundLocalError: local variable 'folder' referenced before assignment
```

**Comment by mortalisk** [comment]
It only works in python 3

**Comment by mortalisk** [comment]
We made a few issues for continued work: https://github.com/equinor/ert/labels/unicorn1
