### ISSUE TITLE
Avoid using yaml.load

### ISSUE THREAD

**Issue by markusdregi** [equinor/libres#681]
We should load yaml safely.

**Comment by berland** [comment]
Yes. Users see warnings from RMS:
`/project/res/komodo/2019.07.02/root/lib/python2.7/site-packages/res/fm/rms/rms_config.py:13: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
`

**Comment by xjules** [comment]
There's one more in stea (`stea_input.py`) but that should be it.
Actually, already fixed by @DanSava, so I reckon this issue can be closed.
