### ISSUE TITLE
Move RETRY callback from enkf_state to python

### ISSUE THREAD

**Issue by ManInFez** [equinor/libres#686]
retry is dependent on the random number generator, which is stored by enkf_mains rng_manager. The rng_manager does not have python bindings. 

Sollution could be either to move the rng_manager into python, or aquire/store the random number in a different manner and reimplement the RETRY callback in python.

**Comment by xjules** [comment]
Explore if `rng_manager` could be retrievable  from `rng_config`

**Comment by xjules** [comment]
Currently, we just cwrap the `rng_manager`, in the future we should replace it by a python rng.
