### ISSUE TITLE
ErtScript gets realEnkfMain as input, should be EnkfMain

### ISSUE THREAD

**Issue by oyvindeide** [equinor/libres#694]
ResScript is required to run internal workflow jobs from Python, and should get EnkfMain as input, it is however getting realEnkfMain.

**Comment by markusdregi** [comment]
Would it be an idea to change the API so that we pass in EnkfMain in the function call, instead of to the constructor?

**Comment by oyvindeide** [comment]
With @ManInFez we narrowed down the problem to the HookManger, meaning that workflows run through the HookManger gets realEnkfMain, and if run directly they get EnkfMain

**Comment by oyvindeide** [comment]
Resolved in https://github.com/equinor/libres/pull/744
