### ISSUE TITLE
Make job queue and job queue manager (more - pure) python

### ISSUE THREAD

**Issue by xjules** [equinor/libres#728]
There are still some cwrap calls (e.g., obtaining job status, etc.), which need to be replaced by the new functionality. See #652 #656  and #684 
Tests need to updated accordingly.
Depends on #686

**Comment by xjules** [comment]
suggestion: could we remove job_queue completely?

**Comment by sondreso** [comment]
The job queue and manager has been refactored in the new evaluator. We are also moving to using other workflow managers
