### ISSUE TITLE
Prettier printing of status.json

### ISSUE THREAD

**Issue by berland** [equinor/libres#736]
I suggest pretty-printing the dumped `status.json` with whitespace, similar to how `jobs.json` is dumped.  
```
 $ wc status.json jobs.json 
    0   717  7852 status.json
 1288  3764 43923 jobs.json
```
(`status.json` is a single line with no \n, very hard to read by a human in a terminal window without `jq` available)

Possible a simple fix, looking at the lines:
https://github.com/equinor/libres/blob/eb8a93b0d6b2b770720d5c273b2647b781f6c655/python/tests/res/job_queue/test_equinor_jobmanager.py#L59
and
https://github.com/equinor/libres/blob/eb8a93b0d6b2b770720d5c273b2647b781f6c655/python/job_runner/reporting/file.py#L184

**Comment by markusdregi** [comment]
Thank you for the suggestion! :+1: This should, as you indicate, be easy to fix.

**Comment by berland** [comment]
Bumping - this would be handy for every occasion where one is debugging other peoples errors.

**Comment by markusdregi** [comment]
We'll get it done 👍
