### ISSUE TITLE
Unstable tests

### ISSUE THREAD

**Issue by oyvindeide** [equinor/libres#737]
Several tests appear to influence each other, some, not all, of these are marked as `pytest.mark.unstable`.

**Comment by oyvindeide** [comment]
The tests are now split into three separate chunks, which run independently, 
`pytest -m "equinor_test and not unstable"`, `pytest -m "not equinor_test"` and `pytest -m "unstable"`. To replicate the problem run `pytest` with all tests (including Equinor specific tests). The tests don't fail gracefully, they fail with `Aborted (core dumped)`, taking down `pytest` with them. Several things have been tried, including stopping test files being produced in the source tree and preventing the manipulating of env. variables during tests. Depending on which tests are being run the problem will manifest itself in different places, and it should be noted that none of the tests marked as unstable are failing. The list of unstable tests is probably not exhaustive.

**Comment by oyvindeide** [comment]
For more context, a lot of tests are keeping file handles open, this could be related to the problem or a coincidence.

**Comment by sondreso** [comment]
We sometimes experienced the mutex error described in https://github.com/equinor/libres/issues/781. Might be related somehow?
