### ISSUE TITLE
STATUS file jobs all on one line

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/libres#764]
With `libres/master` on Python3, I get `STATUS` files of type:
```
Current host                    : SOMEHOST
JOB1            : 19:44:23 .... JOB2                            : 19:44:35 .... JOB3     : 19:44:45 .... 
```
With an earlier stable release, and Python2, I get `STATUS` files of type:
```
Current host                    : SOMEHOST
JOB1            : 19:44:23 .... 19:44:35
JOB2            : 19:44:35 .... 19:44:45
JOB3            : 19:44:45 .... 19:45:10
```
Not sure if this is due to a recent change in `libres` or if it is a Python2/Python3-thing. Seen anything similar? Know what could be the cause?

**Comment by markusdregi** [comment]
Reproduced locally. This should be fixed for the convenience of the user. Thanks for reporting :tada:

Note that if you are to load the data, the `status.json` is much more suitable.

**Comment by jondequinor** [comment]
Output now (using code in the connected PR):
```
Current host                    : be-lx130568/x86_64
sleep_job_0                     : 13:12:19 .... 13:12:19  
…
sleep_job_199                   : 13:12:36 .... 13:12:36  
poly_eval                       : 13:12:36 .... 13:12:36
```
