### ISSUE TITLE
Bug in res config checking

### ISSUE THREAD

**Issue by markusdregi** [equinor/libres#765]
The line checking that exactly one config is passed is faulty. In particular, if all three are passed, the check will pass:

https://github.com/equinor/libres/blob/1297e968a1abdff2a8fba5ba8eb93544d7543dd6/python/res/enkf/res_config.py#L71

**Comment by pinkwah** [comment]
1. Perhaps a bit cryptic and long:
```python3
_assert_configs = ((config is not None) & (config_dict is not None) & (user_config_file is not None)) ^ (config is not None) ^ (config_dict is not None) ^ (user_config_file is not None)
```
2. Same thing, but a bit shorter:
```python3
_assert_configs = (bool(config) & bool(config_dict) & bool(user_config_file)) ^ bool(config) ^ bool(config_dict) ^ bool(user_config_file)
```
3. More concise, and is a bit more future-proof:
```python3
_assert_configs = len([x for x in (config, config_dict, user_config_file) if x]) == 1
```

**Comment by ManInFez** [comment]
I like the last one, but maybe a bit more explicit:
```
_assert_configs = len([x for x in (config, config_dict, user_config_file) if x is not None]) == 1 
```
