### ISSUE TITLE
Kills by MAX_RUNTIME leave few traces on disk

### ISSUE THREAD

**Issue by berland** [equinor/libres#781]
When MAX_RUNTIME is responsible for shutting down a simulation, there are few clues on disk to what went wrong. This typically happens while Eclipse is running, possibly taking too long time due to convergence issues. The Eclipse LOG and PRT files end abruptly, and there is little we can do about this (the OS sometimes puts some error messages on 16pthread_mutex_destroy stuff in the LOG file).

The second trace is the string KeyboardInterrupt in the stderr file for the killed job, but still hard to realize that is was in fact MAX_RUNTIME that was the culprit (unless you have experinenced this before).

The STATUS file and the JOB_LOG file leaves no hints to what happened. Perhaps some hints could be added to text files that users are used to look at.

**Comment by markusdregi** [comment]
> The Eclipse LOG and PRT files end abruptly, and there is little we can do about this (the OS sometimes puts some error messages on 16pthread_mutex_destroy stuff in the LOG file).

Honestly I don't know if there is much we can do about the logs specifically. That Eclipse crashes hard when killed from the outside is beyond the scope of ERT.

What we could do is to log that the forward model has been killed, potentially in the `status.json` and then highlight this in the monitoring in the GUI and CLI. Does that sound like a  good solution?

**Comment by berland** [comment]
Yes!

**Comment by markusdregi** [comment]
Perfect 👍 Thanks for the request!

**Comment by markusdregi** [comment]
Note to developers: This should probably be reformulated as a feature request in the _ERT_ repository

**Comment by markusdregi** [comment]
This information is made available in the GUI in https://github.com/equinor/ert/pull/1636. Makes this information also available in the CLI is captured by https://github.com/equinor/ert/issues/1886
