### ISSUE TITLE
Review usage of SimulationContext masks

### ISSUE THREAD

**Issue by xjules** [equinor/libres#788]
Currently, simulation masks by default are always set to `True` in `BatchSimulator` and thus making their usage redundant. As such they can be removed perhaps.

**Comment by markusdregi** [comment]
Yes, if only consumed by _Everest_, the functionality is not needed. From a different perspective I thing the `BatchSimulator` is currently the most sane API we have for evaluating an ensemble. We should unite the usage of libres from Everest and ERT and when doing so perhaps an iteration of  the `BatchSimulator` could be a good solution. If so, the mask is needed in some way from an ERT perspective.

**Comment by markusdregi** [comment]
This is a won't fix. The entire BatchSimulator will be deprecated.
