### ISSUE TITLE
Convert input to old scaling job into new scaling job

### ISSUE THREAD

**Issue by oyvindeide** [equinor/libres#789]
Several users are using scripts to manipulate the input to the `std_scale_correlated_obs` workflow, which should be native in the new job. Could make a small script which will manipulate the output and facilitate use of the new job.

**Comment by markusdregi** [comment]
Users should instead migrate to the `misfit_preprocessor` job in semeio. An issue to cleanup the workflows was created here: https://github.com/equinor/ert/issues/1880
