### ISSUE TITLE
Magic strings are not replaced in RMS job

### ISSUE THREAD

**Issue by sondreso** [equinor/libres#792]
Magic strings in quotes are not replaced, hence for example the RMS runpath becomes `<RMS_RUNPATH>` and not `rms/model` as intended. 

```
DEFAULT       <RMS_RUNPATH>     rms/model
...
ARGLIST <IENS>  <RMS_PROJECT> <RMS_WORKFLOW> "--run-path=<RMS_RUNPATH>" "--target-file=<RMS_TARGET_FILE>" "--import-path=<RMS_IMPORT_PATH>" "--version=<RMS_VERSION>" "--export-path=<RMS_EXPORT_PATH>"
```

**Comment by oysteoh** [comment]
If the interface towards the RMS script is changed - please update documentation accordingly 
https://github.com/equinor/ert/pull/551
