### ISSUE TITLE
Prevent leaking threads in workflow runner

### ISSUE THREAD

**Issue by ManInFez** [equinor/libres#802]
workflow_runner needs someway of managing threads, perhaps with context manager. In order for our test environment to be sane, we need all spawned threads to be manageable.  Wrokflow_runner.run spawns a thread as a demon an exits. Spawning a thread as a demon should not be the only safeguard for it terminate in due time.

**Comment by markusdregi** [comment]
@ManInFez Can you please verbose the description a bit?

**Comment by xjules** [comment]
The potential solution could be that all python threads are managed by the same thread manager. Which all would be `joined` on demand.
