### ISSUE TITLE
Move scaling job to new jobs repo

### ISSUE THREAD

**Issue by oyvindeide** [equinor/libres#810]
The Scaling Job is just another workflow that should be plugged into ERT via a plugin system.

- [x] New Repo
- [x] Extend ERT API https://github.com/equinor/ert/pull/572
- [x] Build `semeio` pip package
- [x] Manual inclusion of scaling job in Py2 via site-config https://github.com/equinor/ert-statoil/pull/161
- [x] Removal from libres https://github.com/equinor/libres/pull/824
- [x] `ert-statoil` depends on `semeio && ert` and `semeio` depends on `ert`. So as long as python2 is a thing, `ert-statoil` pulls in `semeio`. For python3, `semeio` will be explicitly installed via komodo.

**Comment by sondreso** [comment]
Semeio should depend on ERT and not the other way around :)
