### ISSUE TITLE
Make storage location directory independent

### ISSUE THREAD

**Issue by oyvindeide** [equinor/libres#858]
Currently, EnKFMain stores paths relative from current working directory instead of relative from the config file. This means we're required to chdir into the config directory, thus relying on global state and is very unfriendly to web servers.

**Comment by markusdregi** [comment]
Please provide a bit more information in this issue...

**Comment by pinkwah** [comment]
Updated OP

**Comment by markusdregi** [comment]
This is no longer relevant
