### ISSUE TITLE
Remove bare excepts in site_config.py

### ISSUE THREAD

**Issue by sondreso** [equinor/libres#859]
https://github.com/equinor/libres/blob/master/python/res/enkf/site_config.py contains two bare excepts : https://github.com/equinor/libres/blob/45ffcfeabf900775613ac5e0a2f357a60592609a/python/res/enkf/site_config.py#L93 https://github.com/equinor/libres/blob/45ffcfeabf900775613ac5e0a2f357a60592609a/python/res/enkf/site_config.py#L78

These should be removed.

**Comment by markusdregi** [comment]
Covered by: https://github.com/equinor/ert/issues/1891
