### ISSUE TITLE
Make EnkFMain not a god object

### ISSUE THREAD

**Issue by oyvindeide** [equinor/libres#869]
`EnKFMain` has responsibility for a multitude of things that it probably shouldn't have:

- Several convenience functions, such as `enkf_main_get_log_config` are defined as `res_config_get_log_config(enkf_main_get_res_config(enkf_main))`. We should probably remove such functions.
- Loading of observations. (`enkf_main_load_obs`)
- Adding keyword substitutions (`enkf_main_add_internal_subst_kw`)
- Creating configs (`enkf_main_create_new_config`)
- Installing `util_abort` signals. (`enkf_main_install_SIGNALS`)
- Anything to do with forward models (`enkf_main_load_from_forward_model_from_gui`)
- Exporting data (`enkf_main_export_field`)
- Allocating data for ensembles (`enkf_main_alloc_node_ensemble`)
- "Inflating" nodes (?) (`enkf_main_inflate`)
- (De-)Serialising data (`enkf_main_serialize_dataset`)
- Entire `enkf_main_manage_fs.cpp` should be its own module.

**Comment by markusdregi** [comment]
I call upon thy expansion @dotfloat

**Comment by markusdregi** [comment]
Will be revisited later.
