### ISSUE TITLE
Replace (bool|int|time_t|size_t)_vector etc with something more appropriate (numpy?)

### ISSUE THREAD

**Issue by pinkwah** [equinor/libres#886]

**Comment by joakim-hove** [comment]
See this PR from past where I started on something along these lines: https://github.com/equinor/libecl/pull/586

**Comment by pinkwah** [comment]
Thank you. I had a thorough look through your PR. I didn't understand the behaviour of the `_iset` functions until now.

For libres I think it's more viable to have a top-down approach, where we replace libecl vector usage with standard `std::vector`s with as little reimplementation of the old vector functionality as possible.

**Comment by markusdregi** [comment]
This is a large undertaking that probably should be done for the different parts of the code individually. I don't disagree with the issue, but find it to add little value as is.
