### ISSUE TITLE
"E is not finite" - observation with 0.000 variance not removed

### ISSUE THREAD

**Issue by wouterjdb** [equinor/libres#894]
I have experienced now multiple times, with slightly different setups, that after an X number of iterations I end up with an error saying that "E is not finite".

`E(552,0) = -nan`

When the following test is performed:

https://github.com/equinor/libres/blob/4e90285db47057096d958decb1f76a126d6bbbfb/lib/enkf/obs_data.cpp#L460

While diving into the update log I found that there are one (or a few) observations where the mean and variance of the simulated data is 0.000.

`224 : WWPR_BR-P-20_28_02_2001                    1.175 +/-          100.000  Active   |             0.000 +/-           0.000`

**Some wild guesses/speculations:** Could it be that the `0.000` values are used in a division and thus lead to this error? Shouldn't these observations have been removed in the first place - is there maybe a different tolerance on removing than the rounding that is used afterwards in a division?

**Comment by markusdregi** [comment]
I can replicate the issue with the poly case by replacing the first line in `poly_obs_data.txt` (being `2.8532509308 0.1`) with `2.8532509308 0.0`.

**Comment by markusdregi** [comment]
@eivindsm: What do you think should be the behaviour here? One option is to filter away the observations with zero error, but that could lead to unexpected behaviour. In some way you are saying that you are really certain about something and then ERT just ignores it.

Another is to not allow observations with zero error and hence print an error on loading. I'm more in favour of this, then the above.

A third option would be to try to fix the problem.

An interesting observation is that while the above error of `0.0` reproduces the error, setting the error to `0.0000000001` does not. Which both makes sense. But, if we set it as `2.8532509308 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000    00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001`, going beyond the precision of a double again produces the error. This makes me even less in favour of the first option.

**Comment by wouterjdb** [comment]
We had a quick chat and identified the code where that deactivates points with an ensemble spread of near-zero at the time of an observation.

https://github.com/equinor/libres/blob/59bc1a14b9a18f841395672d7a3e5d5455a5243d/lib/enkf/enkf_analysis.cpp#L128-L135

The default value for `std_cutoff = 1.0e-6`, according to the ERT documentaton. There is support for overwriting this setting by using the super-keyword `UPDATE_SETTINGS`. I'm currently running a test with the following line added to my ERT configuration:

`UPDATE_SETTINGS STD_CUTOFF 0.1`

To be continued....

**Comment by markusdregi** [comment]
Ignore the above; it is the ensemble that collapses, not the observation error that is `0`. @wouterjdb will adjust the `STD_CUTOFF` for ensemble spread and try again.

**Comment by wouterjdb** [comment]
I've now run a test with setting `UPDATE_SETTINGS STD_CUTOFF 0.1`; this has not proven to help. I still ended up with a `-nan` after an x number of iterations.
