### ISSUE TITLE
Avoid forwarding X11 over ssh to compute nodes

### ISSUE THREAD

**Issue by berland** [equinor/libres#895]
Users may get errors like this: 
`/usr/bin/xauth:  error in locking authority file /private/username/.Xauthority`
when running ERT. This can have several causes.

One cause is possibly due to ERT/libres forwarding X11 over its ssh connection to a compute node (?). Suggestion is to use `-x` option to ssh to avoid this

Internal discussion: https://www.yammer.com/statoil.com/#/Threads/show?threadId=949470990

**Comment by markusdregi** [comment]
I failed to reproduce this @berland. Can you? If not, could it be that the users who see this actively enable X-forwarding in the `.ssh`-configuration?

**Comment by berland** [comment]
I can confirm that the user that most recently reported this has `ForwardX11 yes` in his `.ssh/config`.

**Comment by markusdregi** [comment]
Thanks 👍

**Comment by markusdregi** [comment]
We will try to facilitate this in the new configuration system.
