### ISSUE TITLE
Log message level regarding usage of random seed

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/libres#901]
Using `libres`/`ert` in a research project, where we (at least currently) are using `RANDOM_SEED` to be able to better understand different kind of changes in the software stack.

Currently we get a terminal statement of the form:
```
Using RANDOM_SEED: 123456
CRITICAL: 14/02 - 15:34:00  Using RANDOM_SEED: 123456
```
when running `libres`, which looks to come from this line:
https://github.com/equinor/libres/blob/4e90285db47057096d958decb1f76a126d6bbbfb/lib/enkf/rng_config.cpp#L194

Is it a `CRITICAL` log message, or should it be more on level `INFO`/`WARNING` (using [this scale](https://docs.python.org/3/library/logging.html#logging-levels))?

**Comment by markusdregi** [comment]
In the name of science reproducibility is critical 😉

Jokes aside, it is a consequence of that until log level is read from the configuration file, there is really only two log levels (on and off). We are aware of the problem and hope to find better solutions in the future. Until then, this is a won’t fix...
