### ISSUE TITLE
Run libres tests again komodo bleeding nightly

### ISSUE THREAD

**Issue by markusdregi** [equinor/libres#902]
Run unit tests against komodo bleeding nightly on the scout instance. Old job can be found here: https://ci.equinor.com/be/job/libres-komodo-run/

**Comment by ManInFez** [comment]
Will be solved when this connects to the release building pipeline:

https://github.com/equinor/komodo-releases/issues/205

**Comment by ManInFez** [comment]
Solved by https://ci.equinor.com/komodo/job/komodo-test/ running on every build
