### ISSUE TITLE
Default version value for eclipse jobs is invalid

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/libres#904]
The default version defined in the job description file is `version`, and thus `"-v, version"` will be the content that is sent to argparse which will fail on `KeyError`.

https://github.com/equinor/libres/blob/master/share/ert/forward-models/old_style/ECLIPSE100
https://github.com/equinor/libres/blob/master/share/ert/forward-models/old_style/ECLIPSE300

**Comment by markusdregi** [comment]
We are not leaning on `eclrun` for this.
