### ISSUE TITLE
Add job index number to jobs.json

### ISSUE THREAD

**Issue by berland** [equinor/libres#918]
For debugging purposes, the job index would be nice to have inside each entry in `jobs.json`, that matches with the index suffix in the stdout/stderr files.

**Comment by markusdregi** [comment]
You want the element of a list to contains its index in the list? I'm guessing that is not your end goal ;) Could you try to describe what you want to achieve instead of how you want to achieve it?

**Comment by berland** [comment]
Valid point! I think I need to able to trace a stderr file found on RUNPATH  (not having access to the ERT gui, because that might be on another users screen), back to which job that failed. The stderr files in RUNPATH have an integer suffix that is not reflected in the stdout/stderr fields in jobs.json. If the filenames in jobs.json were correct, that would suffice.

**Comment by markusdregi** [comment]
Yes, moving the responsibility of appending the index to the stdout and stderr files from `job_dispatch` to the client is quite natural. We're all busy right now, but will prioritise it when there is time... Thanks for the input 👍

**Comment by markusdregi** [comment]
The index is currently added here: https://github.com/equinor/libres/blob/0b9a07fa89ccb9c67929ffcc2ccd4b5f1f9ca8c5/python/job_runner/job.py#L23

Should be added somewhere here: https://github.com/equinor/libres/blob/c4ccaee89d6f21273b5086cbf62c27780b7d6a2c/lib/job_queue/forward_model.cpp#L177

Note that this will also affect the logic for fetching the standard out and standard error from libres/ert again afterwards...
