### ISSUE TITLE
Odd number of CPU's fail for Eclipse with Python 3

### ISSUE THREAD

**Issue by markusdregi** [equinor/libres#922]
User reported following error:

```
File "/prog/res/komodo/2020.03.rc2-py36/root/lib/python3.6/site-packages/res/fm/ecl/ecl_run.py", line 157, in initMPI
   LSB_MCPU_machine_list = make_LSB_MCPU_machine_list( LSB_MCPU_HOSTS )
 File "/prog/res/komodo/2020.03.rc2-py36/root/lib/python3.6/site-packages/res/fm/ecl/ecl_run.py", line 29, in make_LSB_MCPU_machine_list
   for index in range(len(host_numcpu_list) / 2):
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by pgdr** [comment]
A Python 2→Python 3-transition bug, probably.

In Python 2, `len(host_numcpu_list) / 2` would always be integer, but not in Python 3.  Needs `//`.

**Comment by markusdregi** [comment]
It definitively is ;)

**Comment by pinkwah** [comment]
https://github.com/equinor/libres/blob/cbb7a9609c515616ccb4b54670ba6ce22188e449/python/res/fm/ecl/ecl_run.py#L26-L34

https://github.com/equinor/libres/blob/cbb7a9609c515616ccb4b54670ba6ce22188e449/python/res/fm/ecl/ecl_run.py#L138-L149

As I understand it, `make_LSB_MCPU_machine_list` expects an interlaced list of `(host, num_cpu)`, so dividing by two should always result in an integer. Perhaps they're using it wrong?

**Comment by sondreso** [comment]
Will also happen for even numbers:
```
$ python3                                                           
Python 3.6.8 (default, Jun 11 2019, 15:15:01) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> range(4/2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by pinkwah** [comment]
Oh, I thought Python was smarter than that. Then it should be a trivial fix.
