### ISSUE TITLE
Flaky CI testing due to temporary files

### ISSUE THREAD

**Issue by pinkwah** [equinor/libres#954]
```
Abort called from: util_make_path (/tmp/tmp.12lRf5faVN/libecl/lib/util/util.c:4719) 

Error message: util_make_path: failed to make directory:/tmp/jenkins/test/init_transform/48258656 - aborting
: File exists(17) 
```

We should make sure that all temporary files created during testing are uniquely namespaced. See `pytest`'s `tmpdir`.

**Comment by markusdregi** [comment]
This does probably not come from the same run, but from the random generator of the temp-area implementation hitting the same random string twice. It actually takes surprisingly short time to do so, i.e. a couple of months.

**Comment by markusdregi** [comment]
Use `pytest`'s tmp-dir in Python tests. For the C-tests we could look into increasing the entropy of the generator. The "need to fix it now"-solution is to delete stuff on tmp and possibly make the tmp-cleaner slightly more aggressive.

**Comment by markusdregi** [comment]
This does not seem to be an issue anymore.
