### ISSUE TITLE
Process does not stop when too few realizations left

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/libres#984]
E.g. when you are running
```bash
ert es_mda --weights 4,3,2,1 some_config.ert
```
and all realizations fail, you get the message
```
Simulations failed with the following error: Simulation failed! All realizations failed!
```
and the `ert`/`libres` process exits.

However, if _enough_ realizations fail, but not all, you get some message like
```
** ERROR ** There are 1 active realisations left, which is less than the minimum specified - stopping assimilation.
```
coming from https://github.com/equinor/libres/blob/fbdf4be3c4e0bbbb89b5bc50df0e36568efcc716/lib/enkf/enkf_main.cpp#L1215 but the `ert`/`libres` process does not exit (it just hangs there, with nothing happening). To actually quit, the user e.g. needs to do `Ctrl+C`:
```
** ERROR ** There are 1 active realisations left, which is less than the minimum specified - stopping assimilation.
^C
Killing simulations...
```
to exit the process.

Are there any ERT configuration steps that can be done to exit the process automatically when the `** ERROR ** There are 1 active realisations left, which is less than the minimum specified - stopping assimilation.` appears? Or can/should `ert`/`libres` automatically quit when this happens?

One use case: In https://github.com/equinor/flownet we run ERT through FlowNet (and therefore also CI), and now things occasionally hangs forever, e.g. until the GitHub runner times out after 5-6 hours (despite the realizations actually failing after some minutes).

**Comment by markusdregi** [comment]
Thank you for the thorough report @anders-kiaer! This is indeed not how the behavior should be.

The problem with just exiting is that it would cause unexpected and abrupt exists in the GUI. Instead, what needs to be done is that coherent error codes needs to be passed from the updating module to the UI (being the CLI or the GUI). However, this is a slightly larger endeavor then the single problem you are pointing at here.

**Comment by markusdregi** [comment]
I cannot reproduce this behaviour anymore using the `main` branch of ERT @anders-kiaer. Can you please check again and if the problem is still around open a new issue in the ERT repository?
