### ISSUE TITLE
Expose file operation jobs as workflows

### ISSUE THREAD

**Issue by markusdregi** [equinor/libres#993]
The job located in https://github.com/equinor/libres/tree/master/share/ert/forward-models/shell should be exposed as workflow jobs as well to facilitate creation of folders, etc on the "client" side.

**Comment by jepebe** [comment]
It seems that adding job descriptions for workflows is simple but sharing the underlying scripts might not be. Alternatives:
1. Duplicate the scripts
2. Use the same scripts but with `../../`directory paths.
3. Add an "environment" variable in the _site-config_ that the job descriptions can use to look up the shell scripts. (I do not think this already exists.)

Alternatives ordered by effort.
